---

sudo: false

dist: trusty

language: php

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != hhvm ]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - composer self-update
  - composer global require --no-update hirak/prestissimo:@stable
  - composer global update
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - mkdir -p ~/bin
  - curl -sL https://phar.phpunit.de/phpunit-5.7.phar > ~/bin/phpunit
  - chmod 755 ~/bin/phpunit
  - curl -sL https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar > ~/bin/coveralls
  - chmod 755 ~/bin/coveralls

install:
  - composer install --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - composer phpunit

after_script:
  - composer coveralls

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
